### ISSUE TITLE
Speed Highway Texture issues and missing effect

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#128]
Yay! Speed Highway stuff! No fountain...for now, but that's okay. Still, there's a few things that should be addressed.

1) The grass object that is placed under the clock has a texture problem. It needs its Dreamcast model/texture.
![speed highway texture issue](https://cloud.githubusercontent.com/assets/26051785/25566644/bdd31e10-2da2-11e7-81f2-4e6e9ac145ee.png)

2) The thinner floating platforms in Act 1 also need their Dreamcast model/texture.
![speed highway texture issue 2](https://cloud.githubusercontent.com/assets/26051785/25566651/d340697e-2da2-11e7-8e43-a686c22f4cc8.png)

3) Finally, the thicker floating platforms have this spinning light effect going on in the red corners, which does not happen on SADX.
![speed highway no spinning light](https://cloud.githubusercontent.com/assets/26051785/25566654/ead32356-2da2-11e7-8601-e05dbaab54b4.png)

4) Oh, and also, I noticed that the red lights that blink at the top (Bottom) of the missile object in Tails' Act 1 blink more erratically on SADX, but on Dreamcast, it's a smooth fade in and out.

**Comment by PiKeyAr** [comment]
Looking at the texture issues, it seems that your mod isn't updated properly. There shouldn't be any texture packs for OBJ_HIGHWAY.

**Comment by supercoolsonic** [comment]
The "Textures" folder is completely empty. I deleted it and tried again, but it still happens.

**Comment by PiKeyAr** [comment]
I've pushed an update that restores several more objects I missed, but the clock should've been fine since the previous update. I suggest verifying the mod's integrity if it happens again.

As for the flickering lights, fixing sprites requires complex code hacking, which I'm not interested in for something so inconsequential.

**Comment by supercoolsonic** [comment]
Well, it's cool that you got the floating lights and other objects, but now that texture, the one that was messed up on the smaller platforms, is now messed up on the larger platforms with the new spinning lights. There's a problem with that texture. That has to be it. I've redownloaded and verified the integrity multiple times, even using the SET files that come with the mod, but it still appears as it does in the screenshot. I checked the PVM, and the textures are not the SADX ones, so it's....well, I don't know what it's doing. I'm very confused.

**Comment by PiKeyAr** [comment]
It's obvious that you have a texture pack for OBJ_HIGHWAY somewhere among your mods that are loaded after the DC_SpeedHighway mod, or that the OBJ_HIGHWAY PVMs that come with the mod aren't loaded. The objects show up with messed up textures because they have their SA1 models restored, so they need a non-mirrored texture. But you're loading a mirrored texture for some reason. Whichever the cause, the problem isn't coming from the DC_SpeedHighway mod.

**Comment by PiKeyAr** [comment]
I'm guessing you still have the Autodemo Bell mod enabled? That might be causing it because it's texture pack-based.

**Comment by supercoolsonic** [comment]
*Facepalm* THE BELL MOD. Thanks. Problem solved.

**Comment by PiKeyAr** [comment]
Unfortunately the bell mod will be incompatible with DC mods even if you load it before them. To resolve this, one would have to make a separate version of the mod for original SADX models and SA1 models.

**Comment by supercoolsonic** [comment]
I got it to work with the DC mods. I noticed how it was added in at the end of the global value list in the mod you made, so I opened the OBJ PVM for DC Speed Highway with PVMEditSharp, and just added the "st_bel" texture in at the end. Works flawlessly, and everything looks fine now.
