### ISSUE TITLE
Main Menu Broken (DC Branding)

### ISSUE THREAD

**Issue by KNNSpeed** [PiKeyAr/sadx_dreamcast#38]
Upon starting up the game, going to options right after picking a file, and immediately backing out, this happens (Warning: Large images):

![capture](https://cloud.githubusercontent.com/assets/9886112/22808624/fb212762-eefa-11e6-99c7-44a433087a1a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/9886112/22808627/fce28c80-eefa-11e6-9532-3fa9d06301a8.PNG)

There's also a weird dark roundrect-looking shape in the middle of the menu (right behind "Mini Game Collection").

**Comment by PiKeyAr** [comment]
I've seen this before, but unfortunately I haven't been able to reproduce it consistently (e.g. if you start the game and immediately do the steps you mentioned, it doesn't happen).

However, I came up with a better way to stop titlescreen scrolling (assuming that's what's causing the issue), and I fixed the black rounded rectangle. 

Here's an updated DC Branding mod. Please let me know if you can still reproduce it: https://www.dropbox.com/sh/imv4t6cb89v6zt6/AAD9_6lUEIyA-VdnrAqaiefja?dl=0

**Comment by KNNSpeed** [comment]
No dice. If I keep going in and backing out of options & mini game collection, it still happens.

**Comment by PiKeyAr** [comment]
I've been able to reproduce this. It was a texlist mismatch in AVA_DLG_E.PVM.
To fix it on your end, open the Dropbox link in my previous comment and copy the "AVA_DLG_E" folder from textures to your DC_Branding/textures folder, and delete DC_Branding/system/AVA_DLG_E.PVM. Or just redownload the entire mod, but be sure to delete the DC_Branding folder in your mod folder before updating.

Let me know if you can still reproduce it.

**Comment by KNNSpeed** [comment]
Looks like it's fixed!

**Comment by PiKeyAr** [comment]
Let me know if you run into it again. Closing this for now.
