### ISSUE TITLE
List of Issues with Screenshots

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#57]
Okay, so I have a list of things that I have discovered while playing these awesome mods. I'll provide screenshots, of course.

1) There is a path texture leading to Big's house in the Mystic Ruins along the outer edge of the jungle. I believe this problem is present in the Dreamcast version, too. SADX fixes this, though.
![incorrectly applied](https://cloud.githubusercontent.com/assets/26051785/23348161/4583efae-fc6d-11e6-9692-00d209171487.png)
The texture on the right simply needs to be flipped the other way.

[FIXED]
2) On the Egg Carrier, on both the transformed and untransformed model, near the back, are two models that are not using a texture assigned to it. SADX, again, fixes this. It's as simple as checking a flag, as I discovered in the SA Tools SALVL.
![untextured](https://cloud.githubusercontent.com/assets/26051785/23348213/9be9f2d0-fc6d-11e6-8baa-c813107506cc.png)

[RESOLVED]
3) I've been having a lot of z-fighting issues with the fountain in Casinopolis. When I initially posted my list of discoveries on Dropbox like a fool, PkR said he couldn't reproduce it. Maybe it's a computer issue on my end, but here's the z-fighting in action.
![z-fighting in casino](https://cloud.githubusercontent.com/assets/26051785/23348250/df833dee-fc6d-11e6-869a-aef91fc653bb.png)
And yes, that's a custom pause texture. Feels like a waste not to use the mechanic in SADX where it tells you what mode you're in. I can upload those if you want them.

[FIXED]
4) So in Sky Deck 2, there's a model that has...issues. And I know Super Sonic shouldn't technically count as a problem, since he's only available in Sky Deck through a mod, but when the clouds move, the same kind of problem also occurs.
![part in sky deck 2](https://cloud.githubusercontent.com/assets/26051785/23348284/225975ac-fc6e-11e6-918e-d487901b5fc6.png)
Super Sonic's aura is chopped in half. It's behind the level model.

5) I recently posted this on Dropbox like an even bigger fool, but still. I'll post it here, too. The gates in Windy Valley that are usually placed before each wind current have lots of layering issues. A similar problem used to exist for the red transport mechanism object in Speed Highway in vanilla SADX.
![windy valley layering issues](https://cloud.githubusercontent.com/assets/26051785/23348309/6b680e16-fc6e-11e6-8c8b-3c9038d68f8c.png)
The skybox issue that PkR just reported a few hours ago can also be seen here.

[FIXED]
6) In the Angel Island area of Mystic Ruins, the smaller trees that are part of the level model have their tree trunk textures swapped.
![tree texture problem and the grass](https://cloud.githubusercontent.com/assets/26051785/23348925/410dce3e-fc74-11e6-92ab-5c68343b4d51.png)
The tree is using the texture that should be at the bottom of the tree in the middle. The larger tree model uses the correct textures.

Additionally, I'd like to bring attention to the grass object also seen in the screenshot. This model (or its coding) is not the same as the Dreamcast. For one, it's supposed to use two textures, not one.
![mystic ruins plant dreamcast](https://cloud.githubusercontent.com/assets/26051785/23348964/acd874de-fc74-11e6-83cb-3e4611a26233.png)
I know PkR said that some sound looping couldn't be reproduced, but in case he missed this one, I'll mention it here. On the Dreamcast, the sound that the rustling grass makes loops over and over, but on SADX, it only plays once.

On a slightly unrelated note, I'd like to say that I have ripped the SET layout files for the Angel Island area of Mystic Ruins from the Dreamcast version, and have cleaned up the SET layouts for Sonic, Knuckles, Gamma, and Super Sonic. I removed the palm tree loaded below the cliffside area, and optimized the files for other characters, such as not having the Light Speed Attack upgrade be part of the object list for Knuckles and Gamma, just to save on file size. I also fixed the positioning of some grass, gave each tree that can be touched by the player full, tall collision with collision cylinders and spheres so that you cannot clip through them, and gave certain rocks around the master emerald altar sphere collision, as previously you could just walk right through them. Those pointy rocks were removed in SADX as well, except for one, which was given a collision sphere. If anyone would like these layouts, I can upload them.

Here's the sharp rocks I was referring to, by the way. The one in the distance behind Sonic is the one that was kept for SADX.
![sharp pointy rocks](https://cloud.githubusercontent.com/assets/26051785/23348931/592442b4-fc74-11e6-8729-97d40b9e6d29.png)

Back to the list.

[PARTIALLY FIXED]
7) In the Mystic Ruins Jungle, present in all versions of Sonic Adventure, are a couple of alignment issues with the temple area.
![model alignment](https://cloud.githubusercontent.com/assets/26051785/23348662/ee2ae366-fc71-11e6-8116-d05669379704.png)
![2nd alignment problem](https://cloud.githubusercontent.com/assets/26051785/23348664/f203e32a-fc71-11e6-8385-84fcfbd0ec8a.png)
The first one is definitely more noticeable than the second. Since the upper part of the temple isn't part of the level model itself, it may be tricky to fix, if it's possible to fix at all. I've closely checked the model, and all it needs is a slight scoot to the right. Doing so will not create a seam on the left side.

Also, when looking up at the sky in the jungle at sunset...
![line across sky](https://cloud.githubusercontent.com/assets/26051785/23348754/a328aa8c-fc72-11e6-9730-3cbb0259c35d.png)
...this appears. I'm not sure what's causing it.
Another thing, and this may be a job for the Dreamcast Lighting mod, but the object trees, the kind that are placed around the temple area, in the Mystic Ruins aren't effected by the change of day. At night, the trees stick out. A lot.
![sticking out](https://cloud.githubusercontent.com/assets/26051785/23349654/b8ac997e-fc7a-11e6-8fe2-18ebcc323e46.png)

[FIXED]
8) Near the end of Lost World Act 2, or in Knuckles' level in general, the gravity wall panels have a slight hiccup in their texture. Normally, in vanilla SADX, this happens when the panels line up and you can walk on them.
![lost world gravity panel issue](https://cloud.githubusercontent.com/assets/26051785/23348785/0167f8be-fc73-11e6-9ccc-ec59347bda5c.png)

In the Dreamcast version, I believe the object is meant to take that corner texture, duplicate it and rotate it around to get the full square, but in SADX, that doesn't happen. This texture is straight from the Dreamcast version, too, so I really do think that something was lost in translation. Fixing the texture manually will give this result.
![lost world gravity panel issue corrected](https://cloud.githubusercontent.com/assets/26051785/23348812/3a89be8e-fc73-11e6-81c7-0480868c9181.png)

[RESOLVED]
9) In my game, Perfect Chaos is invisible. Completely not there, except he is there.
![where d he go](https://cloud.githubusercontent.com/assets/26051785/23349107/ca7b0b72-fc75-11e6-9220-cb64c021bc4a.png)
I also reported this on Dropbox like the biggest fool, and PkR said it might be a serious problem with colliding mods or a GPU driver problem or maybe something else.

Here is the list of mods I'm using, in order from top to bottom:
SADXFE - Code
Egg Carrier Ocean Music
Super Sonic
Egg Carrier Garden ocean fix
Idle Chatter
Input Mod
Pause Hide
Smooth Camera
ADX Voices
Updated HUD
SADX Style Water for DC mods
Dreamcast Bosses
Dreamcast Branding
Dreamcast Casinopolis
Dreamcast Egg Carrier
Dreamcast Emerald Coast
Dreamcast Final Egg
Dreamcast Hot Shelter
Dreamcast Ice Cap
Dreamcast Lost World
Dreamcast Mystic Ruins
Dreamcast Past
Dreamcast Red Mountain
Dreamcast Sky Deck
Dreamcast Speed Highway
Dreamcast Station Square
Dreamcast Sub Games
Dreamcast Twinkle Park
Dreamcast Windy Valley
Dreamcast style environment maps
Pallette Lighting
Time of Day
Sound Overhaul 2

The boss still functions fine, but I can't see him.

10) At Big's house, the spinning pinwheels and the spinning lamp all have very noticeable jumps in their animations. Would it be possibly to remedy them?

...And that should about do it for now. Happy to be of assistance, and will check back here frequently to stay in quick contact.

You know what? Here. Here's the links for the layout files, and the custom pause textures, if you're interested.
http://www.megafileupload.com/2M5wX/SETMR01E.BIN
http://www.megafileupload.com/2M5wY/SETMR01K.BIN
http://www.megafileupload.com/2M5wZ/SETMR01L.BIN
http://www.megafileupload.com/Kda2/SETMR01S.BIN
http://www.megafileupload.com/Kda3/CON_REGULAR_E.PVM

Place the layout files in the system folder in the DC Mystic Ruins mod, and the CON_REGULAR_E.PVM file in the system folder for the DC Branding mod.

**Comment by PiKeyAr** [comment]
Thanks for the feedback!

This will take some time to figure out, but a quick question: are you using any other modified SET files, particularly for Casinopolis? The issue in (3) could actually be caused by custom/SADX SET files overriding the SET files in DC mods. In which case the game would load the fountain water twice, since it's made of 2 SET objects in SADX, but it's in the landtable in my implementation.

**Comment by supercoolsonic** [comment]
Ooohhh... That would explain it.  Hold on...

...Yeah, wow. Sure enough. Thanks for the tip. Unfortunately, I believe that knocks those two objects to "unused" status, but oh well. And yes, I do actually use modified SET files. The only one I really kept was the one for Perfect Chaos. I based all my SET files, except for the ones I posted, on the files from the original Fixed Edition mod.

And I guess I should take this opportunity to add one more issue.
![see-through floor](https://cloud.githubusercontent.com/assets/26051785/23351280/d407e0f6-fc85-11e6-8625-00d681b33db5.png)
It's a bit difficult to see, but you can see right through the floor, there, and see the level part past it. The clouds also do not appear.
Would it also be possible to increase the draw distance for those pieces of grass that Fixed Edition restored for Sonic? The object even has a high-res model that animates if the camera is real close up to it, but you'd never really notice it in normal gameplay.

Again, thanks for taking the time to respond. It feels great to help out the community.

**Comment by supercoolsonic** [comment]
So, I just tried out that new mod loader function that literally was just released. I wanted to try it before I went to bed, and....it doesn't work. Not for me, anyway. I downloaded the new mod loader and everything. Am I doing something wrong again?

**Comment by PiKeyAr** [comment]
If you mean the Tornado 2 GUI thing, you need to
1) Enable it in the "Codes" tab at the bottom
2) If you use the HD GUI mod (if not - I need to know why), you need to update it. I pushed an update to Dropbox and MEGA mirrors to support that function.

**Comment by PiKeyAr** [comment]
1) That texture is applied on the entire mesh, which is part of the road going beyond the area in that screenshot, and fixing it would break it in another area, creating a visible seam between the path texture and the grass. SADX has different textures for the jungle area, which is why it looks "fixed", but the problem would come back with SA1 textures.
I'd say it's not a bug, but more like a design issue with the original assets. Not very interested in fixing this, and even if I was I wouldn't really know where to start.

2) Fixed. The SA1 version of the landtable lacks a lot of stuff for those untextured parts, so I had to copy the polys and the UVs from the SADX landtable, so now it looks about the same.

3) Not an issue with the mod itself... I guess?

4) This kind of stuff is extremely difficult to fix without a proper transparency solution. I will sort the meshsets in the models involved, but I can't guarantee that it will resolve the issue. In general, fixing such things requires crazy workarounds that are never perfect. There are many issues like that in the unmodded game as well. The only way to fix all such issues for good would be implementing Dreamcast-like order-independent transparency, which is something I hope to see in SADX one day. On the other hand, if it doesn't happen with the SADX landtable, it may be relatively easy to fix.

5) Same as above, though here I can't do anything other than try poking at the model of the gates and see if it can be sorted. Very unlikely to be fixable.

6) Fixed

Re: the grass object: Looking at the model in question, I'm 99% sure that they changed it because of transparency issues (the part that had a different texture uses an alpha channel, while the other one doesn't). Unfortunately this also means it's going to the same list as (5).

7) The first one - isn't it supposed to be like that?
The second one - one possible solution is to move the bottom part of the temple, but that can potentially break more things than it will fix. I don't think it's worth the trouble.

Re: the skybox in the evening - I've seen that too, even in the Dreamcast version. It may be because of the way the skybox is set up, as it consists of several objects that are joined together. Not sure if it's fixable.

Re: trees ignoring lighting: that's working as intended. Here's a screenshot from the Dreamcast version:

8) Fixed

9) I guess this is also caused by modified SET files, otherwise I have no idea.

**Comment by PiKeyAr** [comment]
Re: Red Mountain platform: I sorted the model, which fixed the weird-looking edges on the grid, but you're actually supposed to see through the floor there. This is what it looks like from under the grid:
![sadxlvl2_2017_02_27_19_26_24_785](https://cloud.githubusercontent.com/assets/23312549/23357890/22f2a82a-fd23-11e6-8019-15027be32345.png)
There's another area before that where the grid has weird edges, but that one can't be fixed because it's a two transparent parts overlapping each other in one mesh.

**Comment by supercoolsonic** [comment]
Thanks again for the help. I got the code working. It's great that you were able to fix to much. I'll continue to look at Perfect Chaos. I'm using the normal layout, so I have no idea what's going on.

**Comment by supercoolsonic** [comment]
Re: 7. I'm pretty sure that isn't intended. One half of the ruins model there is clearly higher than the other, and the model just cuts off. Maybe it is intentional, as it was never fixed in any version of Sonic Adventure, but I doubt it.

In terms of Perfect Chaos, it's probably a problem on my end. I tested the Boss mod alone, and it still happened. I tested the Dreamcast layout, and it still happened. I tested the layout that comes with the mod, and it still happened. I tested the .exe with no mods, and it happens. I tested an .exe that hasn't been touched by the mod loader, and it happens. I tested the .exe with the original 2004 system files, and it still happens. I tested a clean .exe with modified layout files, and it doesn't happen. I was tinkering with level texture lists in the past, and noticed that the list was set to be 18 textures long, instead of 16. I changed that, and it still happens in the modified .exe. So don't worry about it. It's my own issue. Although I can't begin to fathom what's wrong...

Curious that even in the Dreamcast version those trees don't follow the nighttime lighting. Ah well. The purpose of these mods is to be accurate with the Dreamcast version.

I guess I should contribute a few more issues. 

1. The Red Mountain model part in Knuckles' level also has a problem with the bottom part.
![see-through floor 2](https://cloud.githubusercontent.com/assets/26051785/23377375/7655abf8-fcf5-11e6-81f1-7ae252c9ac82.png)
If I may ask, which part of Red Mountain are you referring to that can't be fixed?

2. This may be another thing I should direct towards Fixed Edition, but I don't have a Retro account, so... I came to notice that there's a lot of objects on the Sonic Pinball table. They're called "Emergency", and is object number 82 in the object list. But in-game, I can't see anything there. Is there a way to look into the object's coding and find out what the object does? Seems like a waste to plaster them all over the level if they don't do anything.

The object address seems to be 1D5240, with the text address being 4106F8.

3. In Sky Deck 3, from a distance, I got this to happen to the grid.
![sky deck grid problem](https://cloud.githubusercontent.com/assets/26051785/23377889/2c6327b2-fcf7-11e6-8e0f-ac8fc85d6bb8.png)
Is this related to the clipping issue you mentioned about the moving clouds?

4. In Sonic's version of Sky Deck 3, right here at the end of the platform, there's supposed to be a Unidasu/Orbinaut that appears, but it doesn't show up when loaded on the Dreamcast model. It shows up on the SADX model, though.
![orbinot location](https://cloud.githubusercontent.com/assets/26051785/23378077/b646e018-fcf7-11e6-9712-3c15aaf671b5.png)

5. In Big's Ice Cap, there's an interesting thing going on with this area.
![big s ice cap problem](https://cloud.githubusercontent.com/assets/26051785/23378947/ab15a532-fcfa-11e6-983e-9ecda92bcde2.png)
I think this might also look the same way in the Dreamcast version, but it looks...like it wasn't meant to appear like this. Is there any way to fix it?

6. In Big's secret fishing spot in Emerald Coast, looking up on the island...
![underwater](https://cloud.githubusercontent.com/assets/26051785/23379001/d2b146be-fcfa-11e6-8ba9-08b5b8c0cacb.png)
...gives the impression that you're still underwater. I know this is a problem in SADX, as well. Is this possible to fix, too?

7. Within the "machine room" of the Casinopolis lobby, one of the rotating cylinders has layering problems. Only this one has it. The other two are fine.
![casino machine layering](https://cloud.githubusercontent.com/assets/26051785/23379221/be101b9e-fcfb-11e6-8fa6-328482a9d4fa.png)

8. Layering problems everywhere! Ha ha. Here's another one. Still in Casinopolis, the water has a problem with the flame object.
![water layering](https://cloud.githubusercontent.com/assets/26051785/23379462/a08ccaee-fcfc-11e6-8b9e-7710d4ed6ac7.png)
I also noticed at the fountain again, that the model on the landtable that replaced object MISUB, the waterfall, has layering issues with the water in the fountain.
![water layering fountain](https://cloud.githubusercontent.com/assets/26051785/23379540/e8a10d68-fcfc-11e6-8fb4-e8945c427abc.png)

9. The windows in Speed Highway Act 3 don't layer the shadows of rings and the player correctly. Last layering issue for now.

10. Ummmm....so in Sky Deck Act 1, for some reason, when the clouds move down to change to the darker version of the level, this happens.
![warning warning](https://cloud.githubusercontent.com/assets/26051785/23380272/baa4e6ca-fcff-11e6-8833-582a9fd01f44.png)
Everything gets this pink-red tone. It returns to normal when the clouds move back up. This also happens in Act 2. Perhaps something on my end again? Not sure.

That's all for now. I'll continue to hunt for issues, and report them whenever I find them.

**Comment by supercoolsonic** [comment]
Okay, I re-downloaded the Sky Deck mod, and now that red light issue isn't happening.

**Comment by PiKeyAr** [comment]
Fixed: 1, 3, 4, 5, 8
6 - not fixable at the moment
7 - can't reproduce, and I remember fixing that particular object, so something's odd about this
MIZU B - not fixable without breaking the lights in that area
9 - not fixable without order-independent transparency
10 - looks like a test palette being loaded by the Palette Lighting mod. The mod may be out of date, or the PL files (particularly PL_61B.BIN) have been altered. Either way, this is unlikely to be caused by DC Conversion per se.

This issue cannot be fixed without order-independent transparency:
![untitled](https://cloud.githubusercontent.com/assets/23312549/23396390/0f4a8248-fdd7-11e6-8a90-fe0d49113349.png)

I noticed you were using the Updated HUD mod. You might want to use the "HD Dreamcast Style GUI" mod instead, since it includes the updated HUD from that mod and many more things - pretty much all GUI elements in the game. It should be the last in the list of mods to load.

I would also strongly advise against using modified EXEs, those can cause all sorts of issues I cannot possibly investigate/fix, and the whole point of the Mod Loader was to remove the need for modifying the EXE. Even though the Mod Loader works with modded EXEs, it's generally not recommended to use them.

I've also forwarded your comments where you mentioned SADXFE to the author of SADXFE.

**Comment by supercoolsonic** [comment]
Thank you for your advice and hard work. I've started working on taking a clean .exe and adding simple edits to it, like start positions and typo fixes in a couple of the Mission Mode text. I originally extended the .exe to increase the length of texture lists for certain levels, like Twinkle Park, Lost World, and Red Mountain, so I could add in Dreamcast textures, but I'm not sure what I broke to cause Perfect Chaos to become invisible, or if that's what caused it.

I can't remember fully at the moment. Is there a mod available that allows different characters to play the DLC Twinkle Circuit levels? I know it's possible to edit the .exe to do that, but seeing what's been happening now, I'd rather not. And do the DC conversion mods alter the starting positions?

In future reports, I'll try to avoid reporting layering issues, seeing as pretty much all of them can be fixed by implementing order-independent transparency. Also, that link you posted just makes my computer say that the connection timed out.

About the HD Dreamcast GUI mod, I've tried it out, and everything about the menus are nice and crisp and clear...almost to the point where it sticks out compared to many other textures in the game. This is just my personal opinion, but I feel that if the menus are going to be HD, then an astronomical amount of textures in the game need to be "HD-ified".

1. With all that said, I have one more issue to report. Well, kind of two.

...Okay, that's weird. For some reason, it can't process the screenshots I've taken. Great. ...It's a couple more alignment issues with the ruins around the temple. One of them is on the same side as the one you just fixed, the other is on the right hand side when looking at the temple from the side that has the entrance to Sonic's Lost World.

I'll continue to look for more problems. I'm also curious as to what was causing the Orbinaut to not spawn in. I believe that happens with a Sweep in the pond in Emerald Coast Act 2, and pool of water between the two bowling sections in Twinkle Park, but only on SADX.

**Comment by Thesch28** [comment]
Well here is a mod that allows you to play the DLC twinkle circuit levels but only in Trail mode.
Here's a download link http://u.teknik.io/9v7Efx.zip

**Comment by supercoolsonic** [comment]
Oh ho! Thank you so much! I knew I remembered seeing this somewhere

**Comment by supercoolsonic** [comment]
2. Found another problem. It's back in Lost World Act 3 again. If you stand at the top of the stairs and look up at the ceiling, the ceiling may vanish at points.
![vanishing ceiling](https://cloud.githubusercontent.com/assets/26051785/23436539/8ed71866-fdd0-11e6-9e3c-5dce595882ab.png)

Oh, it's letting me add screenshots again. Here's the alignment issues I mentioned earlier.
![alignment problem yet again](https://cloud.githubusercontent.com/assets/26051785/23436586/b2f76a8e-fdd0-11e6-8752-b7a935609e7c.png)
![alignment problem again](https://cloud.githubusercontent.com/assets/26051785/23436588/b5a0efbc-fdd0-11e6-95cb-7032392182b8.png)

**Comment by PiKeyAr** [comment]
If I remember correctly, the DC mods don't alter start positions (but SADXFE does).

Please keep reporting the layering (transparency) issues, as many of those are fixable without order-independent transparency, and the universal solution is unlikely to show up very soon. I would appreciate it if you opened a new issue, though, because this one is getting harder to follow up and reference in commits.

The DC mods don't touch lighting per se (except material properties, which can change an object's color or make it ignore lighting), so the Sky Deck feedback would be of better use [on the PL mod's issue tracker](https://github.com/SonicFreak94/sadx-dc-lighting/issues).

The Orbinaut issue was caused by different bound values for the landtable object the badnik was supposed to be on top of. Because the bounds were too small, it wasn't processed at the start of the stage, causing the badnik to fall through it. The Dreamcast version also had this problem.

The O TUTUA problem is caused by modified SET files. I replaced that object with another similar-looking one (I forget which, possibly TUTUB or TUTUC) in the SET file. SET layouts from SA1 and SADX also have some minor differences, which may not be immediately obvious, such as missing and misaligned objects in Emerald Coast 2. DC Conversion uses modified Dreamcast SET files for various fixes like this one and the fountain, and you need to use them if you want to play the DC mods. The SET files that come with the mods have most SADXFE layout fixes integrated, too, and include new fixes. If you want to add your own layout fixes, you'd have to adapt them to the SET files included in the DC mods. By the way, I'm interested in integrating some of your fixes (Angel Island rocks) into the mods if it's alright with you.

"Seeing double" - from what I heard, this happens without mods as well. I have no idea on how to fix that.

As for the modified EXE, pretty much everything you mentioned is easier to do with the Mod Loader, for some things (like start positions) you don't even have to make a DLL mod. I see little meaning in editing the EXE now that the Mod Loader is capable of so many things.

**Comment by supercoolsonic** [comment]
Okay. I will make a new issue for each handful of problems I find. And I will continue reporting all layering issues I come across.

You're right that the TUTUA problem is caused by modified SET files. However, in the normal game, Dreamcast too, that object is loaded. To make the smoothest experience possible in there, I understand why the object was replaced. I hope the object itself can be repaired at some point, though.

The mod loader can handle all of that, huh? Hmm.... Well, I have little experience in creating SADX mods myself, so I'll leave that to the professionals for now. I will report the lighting issue over on the respective issue tracker, as you have suggested.

You are more than welcome to use my layout files however you please. You may integrate anything within my layout files into your files for the DC mods. Thank you for wanting to use them.

I am (now) aware that the DC conversion mods aren't entirely 1-to-1 for the Dreamcast, and even some of the layout files straight from the Dreamcast may not work as desired for the most optimal and comfortable experience. May I ask if there's any special code-related changes to the SET files? Or is it just the layout in general? ...My layout files, actually, have been worked on for about four years, now, based on the original Fixed Edition layout files, carefully adjusted to fix a slew of layout problems across the game and optimizing files to save on file size. One such example of optimizing is deleting the entire beta layout in Knuckle's Lost World, which saves a good amount of space. Every stage has additional fixes, and for the layouts that were missing certain things compared to the Dreamcast layout, like Windy Valley, I went through the trouble of comparing them side-by-side back in SADXLVL when that was the primary tool to use, and adding in the objects manually. When there is a conflict with the level models between Dreamcast and SADX, I create alternate files to be loaded within the mods, still containing all the fixes I've done over the years, as well as correcting anything that needs alterations. As such, with the exceptions of such things like Casinopolis, where the objects were integrated into the landtable itself, my layout files should work with the DC mods nearly flawlessly. Emphasis on "should". Until I saw the invisible Perfect Chaos issue, I never saw any real problems with the edits I was making. In fact, everything still works as it should, to my knowledge. The only problems that linger are ones that still exist within the game itself. I've never been suspicious of a problem occurring within the game due to a layout change I made unless I was testing something, and expected something wrong to happen.

...Anyway, thank you for answering some of my own questions. I had never heard of "bound values" before. You learn something new every day. I will continue to track down as many issues as I can. Thanks for your time so far.

**Comment by PiKeyAr** [comment]
Regarding the SET files, I think they are compatible as far as the code goes, but level geometry (landtables) was changed slightly in SADX for almost all levels, and object placement had to be tweaked to match it (for example, if you play Emerald Coast 2 with the DC landtable and SADX SET file, some flowers and grass will be misplaced). They also removed some objects, such as the grassy rocks in some areas of Emerald Coast 2, which were put too close to each other. Running the level with an untouched Dreamcast SET file would cause those objects to have Z fighting, which is probably why they were removed. However, it was easy to correct that without removing them. There are many similar cases in other levels. On top of that, there are several workarounds for alpha-related issues, such as the bathroom lights in Hot Shelter 2, the billboard object on the second floor of Casinopolis, almost all water-related objects in Hot Shelter 1 and many others, for which I had to remove the SET objects and remake them as landtable objects. So all I can say is, SET files intended for SADX levels or untouched DC SET files are not compatible with DC mods.

SADXFE SET files and raw Dreamcast SET files weren't compatible with DC mods for the reasons mentioned above, so I went through all of the SET files and integrated the fixes into my layouts (which is something I'd rather not go through again), but some fixes didn't work correctly or weren't actually needed (e.g. some badniks that were realigned with SADXFE were actually fine with DC level geometry). If you want to convert your fixes for use with DC mods specifically, you could export the SET files as text files using DXEdit, and compare the differences between your SET files and my files.

Also, I'm not quite sure saving space is worth it in case of SET files. All SADX SET files together are less than 1.5MB in size. Given how much unused material the base game has, I don't see much point in this kind of optimization.

**Comment by supercoolsonic** [comment]
This will be my last post in this issue unless another is needed. I guess the SET files aren't that large to begin with, but it can save on load times for weaker computers, that much I'm sure of. Especially with the DC lighting mod. I'll take a look at those levels in general, regarding the SET files. At least now I'm aware that some things may be my own fault. Thanks for letting me know, though.
