### ISSUE TITLE
Twinkle Park textures and material issues

### ISSUE THREAD

**Issue by supercoolsonic** [PiKeyAr/sadx_dreamcast#90]
Heya. I think the latest update to Twinkle Park didn't...go through completely?

1. The bowling launchers still don't have the transparent texture.

2. The textures for the trap doors, and by extent, the floating grey platforms, have been jumbled up badly. The textures for the trapdoor room itself also got screwed up a little, I think.
![platform graphics glitch](https://cloud.githubusercontent.com/assets/26051785/23986564/dd49c0f6-09f2-11e7-87fe-1e65070e609a.png)

3. The buyons are still appearing blue instead of green in the middle.
![buyons are still the same](https://cloud.githubusercontent.com/assets/26051785/23986569/df3725a2-09f2-11e7-8e89-27b0651a2ba4.png)

You said you fixed the Sky Deck issues, yet I noticed Sky Deck wasn't updated. ...Sorry. I'm tired, and I need to go to sleep. Not trying to be mean. Everything else is fine, though. Thanks for your hard work. Keep making all this stuff even more awesome.

**Comment by Zetchzie** [comment]
heres another issue you may have missed @supercoolsonic 

![capture](https://cloud.githubusercontent.com/assets/15071652/23987670/105045d4-0a01-11e7-86b6-b0c89e51387a.PNG)

**Comment by PiKeyAr** [comment]
Yeah, looks like I accidentally removed some code during cleanup. Anyway should be fixed now.

As for the buyons though...
![by2](https://cloud.githubusercontent.com/assets/23312549/23987748/6fa491e4-0a6e-11e7-9e93-27bd7dbb2fdb.png)
![untitled](https://cloud.githubusercontent.com/assets/23312549/23987749/6fa695a2-0a6e-11e7-9916-457ce3e5ac20.png)

>heres another issue you may have missed @supercoolsonic

That happens in the original game too, it's just the way it's designed. It was "fixed" in SADX by removing those floating platforms at the bottom entirely, which I probably won't do since I spent a lot of time restoring and realigning them.

**Comment by supercoolsonic** [comment]
I know this is closed, but I mentioned the grey platforms looking different, and I didn't provide a picture. Well, here's one.
![grey platforms](https://cloud.githubusercontent.com/assets/26051785/24006889/f7337082-0a3a-11e7-9177-e1961f8f6fc4.png)

Also, lucky me for reporting the platforms with this perspective. I noticed that the roller coaster has red lights on it on the Dreamcast that aren't lit on SADX.

**Comment by PiKeyAr** [comment]
I don't really know about the Buyon behavior. Anyway I've made corrections to all of the above, feel free to reopen this issue if you find anything else in this level.

**Comment by supercoolsonic** [comment]
Will do. However...
![still having some problems](https://cloud.githubusercontent.com/assets/26051785/24016734/4c8b9864-0a5b-11e7-8aad-54513efc287d.png)

These trapdoors just do not want to be fixed, huh?

Everything else is fine.

**Comment by Zetchzie** [comment]
looks like the Floating platform textures are different in DC
